### ISSUE TITLE
Rails 6 (Active Record with Postgres)

### ISSUE THREAD

**Issue by yoshie902a** [ankane/the-ultimate-guide-to-ruby-timeouts#30]
Found your guide, very helpful!

If I am running Rails 6 with Postgres, Sidekiq, Redis on Heroku what timeout settings do you recommend? You stated Postgres was the most important, but what would be 2nd and 3rd?  Also, do you have examples of how best to rescue a timeout?  Especially Postgres timeouts?  

It seems setting the database.yml will setup the database. But you also mentioned a way to setup ActiveRecord.  Is one preferred? Does the ActiveRecord version prevent the migration timeout issue?

production:
  variables:
    statement_timeout: 5s # or ms, min, etc

**Comment by ankane** [comment]
Hey @yoshie902a, for Postgres, I would recommend something like:

```yml
production:
  connect_timeout: 3
  variables:
    statement_timeout: 5s
```

And for Redis:

```rb
Redis.new(connect_timeout: 3, timeout: 3, ...)
```

I wouldn't bother rescuing timeouts in most cases (just let the app return 500 errors). If you have critical code that needs special handling, you can rescue timeout exceptions and handle as needed.

For migrations, if you use [Strong Migrations](https://github.com/ankane/strong_migrations), it can set a separate statement timeout for migrations. Otherwise, you'll need to use the statement timeout pattern in this guide.

**Comment by ankane** [comment]
Cleaning up issues
